---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-catalog
  namespace: nordmart-demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
    sidecar.istio.io/inject: "true"
spec:
  releaseName: nordmart-dev-catalog
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "catalog"
    deployment:
      podLabels:
        app: catalog
      volumes: {}
      image:
        repository: stakater/stakater-nordmart-catalog
        tag: v0.0.2
      fluentdConfigAnnotations:
        regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+)
          (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
        regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
        timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      env:
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: mysql_username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: mysql_password
      - name: MYSQL_HOST
        value: "mysql-svc.nordmart-demo.svc.cluster.local"
      - name: MYSQL_DB_NAME
        value: "catalog"
      - name: KEYCLOAK_REALM
        value: "nordmart"
      - name: KEYCLOAK_URL
        value: "https://keycloak-dev.stakater-200205-1-5c84fa685b23fe4798253ee758d532d0-0000.eu-de.containers.appdomain.cloud/auth/"
      - name: KEYCLOAK_CLIENT_BACKEND
        value: "stakater-nordmart-backend"
      - name: KEYCLOAK_CLIENT_SECRET_KEY
        value: "7672aea2-81ff-4aa2-affe-daf3bad10334"
      - name: KAFKA_ADDRESS
        value: "kafka-cluster-kafka-bootstrap.nordmart-demo:9092"
      - name: JAEGER_ENDPOINT
        value: "http://jaeger-collector.istio-system:14268/api/traces"

      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080

    service:
      ports:
      - port: 8080
        name: https
        targetPort: 8080
    rbac:
      create: true
      serviceAccount:
        create: true
    configMap:
      enabled: false
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: catalog-policy
#  namespace: nordmart-dev-apps
#spec:
#  selector:
#    matchLabels:
#      app: catalog
#  rules:
#    - from:
#        - source:
#            principals: ["cluster.local/ns/nordmart-dev-apps/sa/gateway"]
#      to:
#        - operation:
#            methods: ["*"]