apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-svc
  namespace: nordmart-demo
spec:
  ports:
    - name: "elasticsearch-port"
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: nordmart-demo
spec:
  serviceName: "elasticsearch"
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:7.5.1
          name: elasticsearch
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: elasticsearch_password
            - name: discovery.type
              value: "single-node"
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
              name: tcp
          volumeMounts:
           - mountPath: /data
             name: elasticsearch-pvc
  volumeClaimTemplates:
   - metadata:
       name: elasticsearch-pvc
     spec:
       accessModes: [ "ReadWriteOnce" ]
       storageClassName: ibmc-block-gold
       resources:
         requests:
           storage: 5Gi