---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-gateway
  namespace: nordmart-demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
    sidecar.istio.io/inject: "true"
spec:
  releaseName: nordmart-dev-gateway
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "gateway"
    deployment:
      podLabels:
        app: gateway
      image:
        repository: stakater/stakater-nordmart-gateway-vertx
        tag: v0.0.1
      fluentdConfigAnnotations:
        regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+)
          (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
        regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
        timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080
      volumes: {}
      env:
      - name: CATALOG_API_HOST
        value: "catalog.nordmart-demo.svc.cluster.local"
      - name: CATALOG_API_PORT
        value: "8080"
      - name: CUSTOMER_API_HOST
        value: "customer.nordmart-demo.svc.cluster.local"
      - name: CUSTOMER_API_PORT
        value: "8080"
      - name: INVENTORY_API_HOST
        value: "inventory.nordmart-demo.svc.cluster.local"
      - name: INVENTORY_API_PORT
        value: "8080"
      - name: DISABLE_CART_DISCOVERY
        value: "false"
      - name: CART_API_HOST
        value: "cart.nordmart-demo.svc.cluster.local"
      - name: CART_API_PORT
        value: "8080"
      - name: HTTP_PORT
        value: "8080"
      - name: REVIEW_API_HOST
        value: "review.nordmart-demo.svc.cluster.local"
      - name: REVIEW_API_PORT
        value: "8080"
      - name: PRODUCT_SEARCH_API_HOST
        value: "search.nordmart-demo.svc.cluster.local"
      - name: PRODUCT_SEARCH_API_PORT
        value: "8080"
      - name: JAEGER_ENDPOINT
        value: "http://jaeger-collector.istio-system:14268/api/traces"
    service:
      annotations:
        config.xposer.stakater.com/Domain: nordmart-eks.stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}'
        config.xposer.stakater.com/IngressURLTemplate: gateway-dev.{{.Domain}}
        config.xposer.stakater.com/TLS: "true"
        config.xposer.stakater.com/TLSSecretNameTemplate: tls-cert
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: internal-ingress
          ingress.kubernetes.io/force-ssl-redirect: false
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          exposeIngressUrl: globally
      ports:
      - port: 8080
        name: https
        targetPort: 8080
    rbac:
      create: true
      serviceAccount:
        # create: true
        name: default
    configMap:
      enabled: false
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: gateway-dev-virtualservice
#   namespace: istio-system
# spec:
#   hosts:
#     - "gateway-dev.nordmart-eks.stakater.com"
#   gateways:
#     - istio-gateway
#   http:
#     - route:
#         - destination:
#             host: gateway.nordmart-dev-apps.svc.cluster.local