---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-inventory
  namespace: nordmart-demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
    sidecar.istio.io/inject: "true"
spec:
  releaseName: nordmart-dev-inventory
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "inventory"
    deployment:
      podLabels:
        app: inventory
      volumes: {}
      image:
        repository: stakater/stakater-nordmart-inventory
        tag: v0.0.2
      env:
      - name: JAEGER_ENDPOINT
        value: "http://jaeger-collector.istio-system:14268/api/traces"
      fluentdConfigAnnotations:  
          regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+) (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
          regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
          timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 15
          httpGet:
            path: /healthCheck
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 15
          httpGet:
            path: /healthCheck
            port: 8080
    service:
      ports:
      - port: 8080
        name: https
        targetPort: 8080
    rbac:
      create: true
      serviceAccount:
        create: true
    configMap:
      enabled: false
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: inventory-policy
#  namespace: nordmart-dev-apps
#spec:
#  selector:
#    matchLabels:
#      app: inventory
#  rules:
#    - from:
#        - source:
#            principals: ["cluster.local/ns/nordmart-dev-apps/sa/gateway"]
#      to:
#        - operation:
#            methods: ["GET", "POST"]