---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-search
  namespace: nordmart-demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
    sidecar.istio.io/inject: "true"
spec:
  releaseName: nordmart-dev-search
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "search"
    deployment:
      podLabels:
        app: search
      volumes: {}
      image:
        repository: stakater/stakater-nordmart-search
        tag: v0.0.1
      fluentdConfigAnnotations:
        regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+)
          (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
        regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
        timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      env:
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secret
            key: elasticsearch_password
      - name: ELASTICSEARCH_HOST
        value: "elasticsearch-svc.nordmart-demo"
      - name: ELASTICSEARCH_PORT
        value: "9200"
      - name: KAFKA_ADDRESS
        value: "kafka-cluster-kafka-bootstrap.nordmart-demo"
      - name: KAFKA_PORT
        value: "9092"
      - name: JAEGER_ENDPOINT
        value: "http://jaeger-collector.istio-system:14268/api/traces"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080
    service:
      ports:
      - port: 8080
        name: https
        targetPort: 8080
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false