---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-web
  namespace: nordmart-demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
    sidecar.istio.io/inject: "true"
spec:
  releaseName: nordmart-dev-web
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "web"
    deployment:
      podLabels:
        app: web
      image:
        repository: stakater/stakater-nordmart-web
        tag: v0.0.4
      fluentdConfigAnnotations:
        regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+)
          (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
        regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
        timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
      volumes: {}
      env:
      - name: PORT
        value: "4200"
      - name: SECURE_GW_ENDPOINT
        value: "https://gateway-dev.stakater-200205-1-5c84fa685b23fe4798253ee758d532d0-0000.eu-de.containers.appdomain.cloud"
      - name: NORDMART_GW_ENDPOINT
        value: "https://gateway-dev.stakater-200205-1-5c84fa685b23fe4798253ee758d532d0-0000.eu-de.containers.appdomain.cloud"
      - name: SSO_URL
        value: "https://keycloak-dev.stakater-200205-1-5c84fa685b23fe4798253ee758d532d0-0000.eu-de.containers.appdomain.cloud/auth/"
      - name: SSO_REALM
        value: "nordmart"
      - name: SSO_CLIENT_ID
        value: "stakater-nordmart-web"
      - name: JAEGER_ENDPOINT
        value: "http://jaeger-collector.istio-system:14268/api/traces"
    service:
      annotations:
        config.xposer.stakater.com/Domain: nordmart-eks.stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}'
        config.xposer.stakater.com/IngressURLTemplate: web-dev.{{.Domain}}
        config.xposer.stakater.com/TLS: "true"
        config.xposer.stakater.com/TLSSecretNameTemplate: tls-cert
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: internal-ingress
          ingress.kubernetes.io/force-ssl-redirect: false
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          exposeIngressUrl: globally
      ports:
      - port: 4200
        name: web
        protocol: TCP
        targetPort: 4200
    rbac:
      create: true
      serviceAccount:
        create: true
    configMap:
      enabled: false
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: web-dev-virtualservice
#   namespace: istio-system
# spec:
#   hosts:
#     - "web-dev.nordmart-eks.stakater.com"
#   gateways:
#     - istio-gateway
#   http:
#     - route:
#         - destination:
#             host: web.nordmart-dev-apps.svc.cluster.local
