---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-catalog
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
spec:
  releaseName: nordmart-dev-catalog
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "catalog"
    deployment:
      podLabels:
        app: catalog
      volumes: {}
      image:
        repository: docker-delivery.cp-stakater.com:443/stakater-lab/catalog
        tag: 0.0.0-PR-21-3-SNAPSHOT
      imagePullSecrets: "docker-registry-nexus-secret"
      fluentdConfigAnnotations:
        regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+)
          (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
        regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
        timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      env:
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: mysql_password

      - name: MYSQL_HOST
        value: "mysql-svc.nordmart-dev-apps.svc.cluster.local "

      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080

    service:
      ports:
      - port: 8080
        name: https
        targetPort: 8080
      additionalLabels:
        expose: "true"
      annotations:
        config.xposer.stakater.com/Domain: cp-stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-dev'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-dev.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
