---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-dev-gateway
  namespace: nordmart-dev-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: regexp:^([0-9]+.[0-9]+.[0-9]+-PR-[0-9]{2}-[0-9]+-SNAPSHOT)$
spec:
  releaseName: nordmart-dev-gateway
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "gateway"
    deployment:
      podLabels:
        app: gateway
      image:
        repository: stakater/stakater-nordmart-gateway
        tag: v0.0.1
      imagePullSecrets: "docker-registry-nexus-secret"
      fluentdConfigAnnotations:
        regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+)
          (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
        regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
        timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080
      volumes: {}
      env:
      - name: CATALOG_API_HOST
        value: "catalog.nordmart-dev-apps"
      - name: CATALOG_API_PORT
        value: "8080"
      - name: INVENTORY_API_HOST
        value: "inventory.nordmart-dev-apps"
      - name: INVENTORY_API_PORT
        value: "8080"
      - name: DISABLE_CART_DISCOVERY
        value: "false"
      - name: CART_API_HOST
        value: "cart.nordmart-dev-apps"
      - name: CART_API_PORT
        value: "8080"
      - name: HTTP_PORT
        value: "8080"
      - name: REVIEW_API_HOST
        value: "review.nordmart-dev-apps"
      - name: REVIEW_API_PORT
        value: "8080"
    service:
      ports:
      - port: 8080
        name: https
        targetPort: 8080
      additionalLabels:
        expose: "true"
      annotations:
        config.xposer.stakater.com/Domain: nordmart-aks.stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-dev'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-dev.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
